### ISSUE TITLE
Could not find a version that satisfies the requirement tensorflow==1.15.2

### ISSUE THREAD

**Issue by bigcurry** [streamlit/demo-face-gan#6] opened 2020-06-22 14:07 UTC
After running requirements.txt I was not able to run streamlit. Is there another Tensorflow version compatible?

**Comment by randyzwitch** [comment] 2020-06-22 16:27
Thanks for reporting @bigcurry, it looks like there might have been a broken push on the tensorflow side, which has unfortunate side-effects

https://github.com/tensorflow/tensorflow/issues/36347

I'll try and find someone internally who can troubleshoot this and/or fix it myself

**Comment by bigcurry** [comment] 2020-06-22 17:02
Thanks @randyzwitch!

**Comment by randyzwitch** [comment] 2020-06-25 18:52
Hi @bigcurry - 

I took a look at this, if you use a fresh environment and Python 3.6, this demo does work as expected.

```python
(base) rzwitch@threadripper:~/github_work/demo-face-gan$ conda create -n gandemo python=3.6 -y
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/rzwitch/miniconda3/envs/gandemo

  added / updated specs:
    - python=3.6


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2020.6.20          |           py36_0         156 KB
    pip-20.1.1                 |           py36_1         1.8 MB
    python-3.6.10              |       h7579374_2        29.7 MB
    setuptools-47.3.1          |           py36_0         514 KB
    ------------------------------------------------------------
                                           Total:        32.2 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2020.1.1-0
  certifi            pkgs/main/linux-64::certifi-2020.6.20-py36_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libedit            pkgs/main/linux-64::libedit-3.1.20191231-h7b6447c_0
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_1
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1g-h7b6447c_0
  pip                pkgs/main/linux-64::pip-20.1.1-py36_1
  python             pkgs/main/linux-64::python-3.6.10-h7579374_2
  readline           pkgs/main/linux-64::readline-8.0-h7b6447c_0
  setuptools         pkgs/main/linux-64::setuptools-47.3.1-py36_0
  sqlite             pkgs/main/linux-64::sqlite-3.32.3-h62c20be_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  wheel              pkgs/main/linux-64::wheel-0.34.2-py36_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3



Downloading and Extracting Packages
certifi-2020.6.20    | 156 KB    | ############################################################################################################################################################################################# | 100% 
setuptools-47.3.1    | 514 KB    | ############################################################################################################################################################################################# | 100% 
python-3.6.10        | 29.7 MB   | ############################################################################################################################################################################################# | 100% 
pip-20.1.1           | 1.8 MB    | ############################################################################################################################################################################################# | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate gandemo
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) rzwitch@threadripper:~/github_work/demo-face-gan$ conda activate gandemo
(gandemo) rzwitch@threadripper:~/github_work/demo-face-gan$ pip install -r requirements.txt
Collecting matplotlib>=2.2.2
  Downloading matplotlib-3.2.2-cp36-cp36m-manylinux1_x86_64.whl (12.4 MB)
     |████████████████████████████████| 12.4 MB 2.1 MB/s 
Collecting six>=1.11.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting scipy>=1.1.0
  Downloading scipy-1.5.0-cp36-cp36m-manylinux1_x86_64.whl (25.9 MB)
     |████████████████████████████████| 25.9 MB 5.4 MB/s 
Collecting h5py>=2.7.1
  Downloading h5py-2.10.0-cp36-cp36m-manylinux1_x86_64.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 41.3 MB/s 
Collecting pandas>=0.22.0
  Downloading pandas-1.0.5-cp36-cp36m-manylinux1_x86_64.whl (10.1 MB)
     |████████████████████████████████| 10.1 MB 8.0 MB/s 
Collecting numpy>=1.15.1
  Downloading numpy-1.19.0-cp36-cp36m-manylinux2010_x86_64.whl (14.6 MB)
     |████████████████████████████████| 14.6 MB 9.2 MB/s 
Collecting cryptography>=2.1.4
  Using cached cryptography-2.9.2-cp35-abi3-manylinux2010_x86_64.whl (2.7 MB)
Collecting Pillow>=5.3.0
  Using cached Pillow-7.1.2-cp36-cp36m-manylinux1_x86_64.whl (2.1 MB)
Collecting keras>=2.2.4
  Downloading Keras-2.4.3-py2.py3-none-any.whl (36 kB)
Collecting lmdb>=0.94
  Using cached lmdb-0.98.tar.gz (869 kB)
Collecting moviepy>=0.2.3.5
  Using cached moviepy-1.0.3.tar.gz (388 kB)
Collecting scikit_learn>=0.20.0
  Downloading scikit_learn-0.23.1-cp36-cp36m-manylinux1_x86_64.whl (6.8 MB)
     |████████████████████████████████| 6.8 MB 12.2 MB/s 
Collecting opencv-python>=3.4.0.12
  Downloading opencv_python-4.2.0.34-cp36-cp36m-manylinux1_x86_64.whl (28.2 MB)
     |████████████████████████████████| 28.2 MB 1.7 MB/s 
Collecting tensorflow==1.15.2
  Downloading tensorflow-1.15.2-cp36-cp36m-manylinux2010_x86_64.whl (110.5 MB)
     |████████████████████████████████| 110.5 MB 30.6 MB/s 
Collecting streamlit==0.57.0
  Downloading streamlit-0.57.0-py2.py3-none-any.whl (7.1 MB)
     |████████████████████████████████| 7.1 MB 29.0 MB/s 
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.2.0-cp36-cp36m-manylinux1_x86_64.whl (88 kB)
     |████████████████████████████████| 88 kB 4.6 MB/s 
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting pytz>=2017.2
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting cffi!=1.11.3,>=1.8
  Downloading cffi-1.14.0-cp36-cp36m-manylinux1_x86_64.whl (399 kB)
     |████████████████████████████████| 399 kB 30.9 MB/s 
Collecting pyyaml
  Using cached PyYAML-5.3.1.tar.gz (269 kB)
Collecting decorator<5.0,>=4.0.2
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting tqdm<5.0,>=4.11.2
  Using cached tqdm-4.46.1-py2.py3-none-any.whl (63 kB)
Collecting requests<3.0,>=2.8.1
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting proglog<=1.0.0
  Downloading proglog-0.1.9.tar.gz (10 kB)
Collecting imageio<3.0,>=2.5
  Downloading imageio-2.8.0-py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 17.2 MB/s 
Collecting imageio_ffmpeg>=0.2.0
  Downloading imageio_ffmpeg-0.4.2-py3-none-manylinux2010_x86_64.whl (26.9 MB)
     |████████████████████████████████| 26.9 MB 4.0 MB/s 
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Collecting joblib>=0.11
  Using cached joblib-0.15.1-py3-none-any.whl (298 kB)
Collecting tensorboard<1.16.0,>=1.15.0
  Downloading tensorboard-1.15.0-py3-none-any.whl (3.8 MB)
     |████████████████████████████████| 3.8 MB 30.1 MB/s 
Collecting keras-preprocessing>=1.0.5
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Collecting astor>=0.6.0
  Using cached astor-0.8.1-py2.py3-none-any.whl (27 kB)
Collecting grpcio>=1.8.6
  Downloading grpcio-1.30.0-cp36-cp36m-manylinux2010_x86_64.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 37.9 MB/s 
Collecting protobuf>=3.6.1
  Downloading protobuf-3.12.2-cp36-cp36m-manylinux1_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 7.4 MB/s 
Collecting keras-applications>=1.0.8
  Using cached Keras_Applications-1.0.8-py3-none-any.whl (50 kB)
Collecting gast==0.2.2
  Downloading gast-0.2.2.tar.gz (10 kB)
Collecting opt-einsum>=2.3.2
  Using cached opt_einsum-3.2.1-py3-none-any.whl (63 kB)
Collecting tensorflow-estimator==1.15.1
  Downloading tensorflow_estimator-1.15.1-py2.py3-none-any.whl (503 kB)
     |████████████████████████████████| 503 kB 45.9 MB/s 
Collecting absl-py>=0.7.0
  Using cached absl-py-0.9.0.tar.gz (104 kB)
Collecting termcolor>=1.1.0
  Using cached termcolor-1.1.0.tar.gz (3.9 kB)
Collecting wrapt>=1.11.1
  Using cached wrapt-1.12.1.tar.gz (27 kB)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /home/rzwitch/miniconda3/envs/gandemo/lib/python3.6/site-packages (from tensorflow==1.15.2->-r requirements.txt (line 14)) (0.34.2)
Collecting google-pasta>=0.1.6
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Processing /home/rzwitch/.cache/pip/wheels/25/94/87/c9e81967b98f25a0c0064f42ce71d494c9df4164f613ccee92/watchdog-0.10.2-py3-none-any.whl
Collecting base58
  Using cached base58-2.0.1-py3-none-any.whl (4.3 kB)
Collecting packaging
  Using cached packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting cachetools>=4.0
  Using cached cachetools-4.1.0-py3-none-any.whl (10 kB)
Collecting future
  Using cached future-0.18.2.tar.gz (829 kB)
Collecting click>=7.0
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting botocore>=1.13.44
  Using cached botocore-1.17.10-py2.py3-none-any.whl (6.3 MB)
Collecting tzlocal
  Using cached tzlocal-2.1-py2.py3-none-any.whl (16 kB)
Processing /home/rzwitch/.cache/pip/wheels/64/74/71/e7a0d0eb4fc42cb20a17aec36f8f0b5b8c5e1ec19c701fd34a/tornado-5.1.1-cp36-cp36m-linux_x86_64.whl
Processing /home/rzwitch/.cache/pip/wheels/4f/4a/93/c5ed8c11fedbe97fb8b8032b301eaa736248684b44087a7259/blinker-1.4-py3-none-any.whl
Collecting toml
  Using cached toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting enum-compat
  Using cached enum_compat-0.0.3-py3-none-any.whl (1.3 kB)
Collecting boto3
  Using cached boto3-1.14.10-py2.py3-none-any.whl (128 kB)
Collecting pydeck>=0.1.dev5
  Using cached pydeck-0.4.0b2-py2.py3-none-any.whl (4.4 MB)
Collecting altair>=3.2.0
  Using cached altair-4.1.0-py3-none-any.whl (727 kB)
Collecting validators
  Using cached validators-0.15.0.tar.gz (27 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Requirement already satisfied: certifi>=2017.4.17 in /home/rzwitch/miniconda3/envs/gandemo/lib/python3.6/site-packages (from requests<3.0,>=2.8.1->moviepy>=0.2.3.5->-r requirements.txt (line 11)) (2020.6.20)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.9-py2.py3-none-any.whl (58 kB)
Collecting werkzeug>=0.11.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting markdown>=2.6.8
  Downloading Markdown-3.2.2-py3-none-any.whl (88 kB)
     |████████████████████████████████| 88 kB 2.6 MB/s 
Requirement already satisfied: setuptools>=41.0.0 in /home/rzwitch/miniconda3/envs/gandemo/lib/python3.6/site-packages (from tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.2->-r requirements.txt (line 14)) (47.3.1.post20200622)
Processing /home/rzwitch/.cache/pip/wheels/42/ea/90/e37d463fb3b03848bf715080595de62545266f53dd546b2497/pathtools-0.1.2-py3-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1
  Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting docutils<0.16,>=0.10
  Using cached docutils-0.15.2-py3-none-any.whl (547 kB)
Collecting s3transfer<0.4.0,>=0.3.0
  Using cached s3transfer-0.3.3-py2.py3-none-any.whl (69 kB)
Collecting traitlets>=4.3.2
  Using cached traitlets-4.3.3-py2.py3-none-any.whl (75 kB)
Collecting jinja2>=2.10.1
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting ipywidgets>=7.0.0
  Using cached ipywidgets-7.5.1-py2.py3-none-any.whl (121 kB)
Collecting ipykernel>=5.1.2; python_version >= "3.4"
  Using cached ipykernel-5.3.0-py3-none-any.whl (119 kB)
Collecting jsonschema
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting entrypoints
  Using cached entrypoints-0.3-py2.py3-none-any.whl (11 kB)
Processing /home/rzwitch/.cache/pip/wheels/fc/da/2e/27e381e9cfc922d078a0a750c7ec72e76df66100e81722516d/toolz-0.10.0-py3-none-any.whl
Collecting importlib-metadata; python_version < "3.8"
  Downloading importlib_metadata-1.6.1-py2.py3-none-any.whl (31 kB)
Collecting ipython-genutils
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl (27 kB)
Collecting ipython>=4.0.0; python_version >= "3.3"
  Using cached ipython-7.15.0-py3-none-any.whl (783 kB)
Collecting nbformat>=4.2.0
  Using cached nbformat-5.0.7-py3-none-any.whl (170 kB)
Collecting widgetsnbextension~=3.5.0
  Using cached widgetsnbextension-3.5.1-py2.py3-none-any.whl (2.2 MB)
Collecting jupyter-client
  Using cached jupyter_client-6.1.3-py3-none-any.whl (106 kB)
Collecting attrs>=17.4.0
  Using cached attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Processing /home/rzwitch/.cache/pip/wheels/d1/8a/1c/32ab9017418a2c64e4fbaf503c08648bed2f8eb311b869a464/pyrsistent-0.16.0-cp36-cp36m-linux_x86_64.whl
Collecting zipp>=0.5
  Using cached zipp-3.1.0-py3-none-any.whl (4.9 kB)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Using cached prompt_toolkit-3.0.5-py3-none-any.whl (351 kB)
Collecting pexpect; sys_platform != "win32"
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting jedi>=0.10
  Using cached jedi-0.17.1-py2.py3-none-any.whl (1.4 MB)
Collecting backcall
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting pygments
  Using cached Pygments-2.6.1-py3-none-any.whl (914 kB)
Collecting jupyter-core
  Using cached jupyter_core-4.6.3-py2.py3-none-any.whl (83 kB)
Collecting notebook>=4.4.1
  Using cached notebook-6.0.3-py3-none-any.whl (9.7 MB)
Collecting pyzmq>=13
  Downloading pyzmq-19.0.1-cp36-cp36m-manylinux1_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 3.0 MB/s 
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting ptyprocess>=0.5
  Using cached ptyprocess-0.6.0-py2.py3-none-any.whl (39 kB)
Collecting parso<0.8.0,>=0.7.0
  Using cached parso-0.7.0-py2.py3-none-any.whl (100 kB)
Collecting terminado>=0.8.1
  Using cached terminado-0.8.3-py2.py3-none-any.whl (33 kB)
Collecting Send2Trash
  Using cached Send2Trash-1.5.0-py3-none-any.whl (12 kB)
Collecting prometheus-client
  Using cached prometheus_client-0.8.0-py2.py3-none-any.whl (53 kB)
Collecting nbconvert
  Using cached nbconvert-5.6.1-py2.py3-none-any.whl (455 kB)
Collecting testpath
  Using cached testpath-0.4.4-py2.py3-none-any.whl (163 kB)
Collecting bleach
  Using cached bleach-3.1.5-py2.py3-none-any.whl (151 kB)
Collecting defusedxml
  Using cached defusedxml-0.6.0-py2.py3-none-any.whl (23 kB)
Processing /home/rzwitch/.cache/pip/wheels/46/c4/40/718c6fd14c2129ccaee10e0cf03ef6c4d01d98cad5dbbfda38/pandocfilters-1.4.2-py3-none-any.whl
Collecting mistune<2,>=0.8.1
  Using cached mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Collecting webencodings
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: lmdb, moviepy, pyyaml, proglog, gast, absl-py, termcolor, wrapt, future, validators
  Building wheel for lmdb (setup.py) ... done
  Created wheel for lmdb: filename=lmdb-0.98-cp36-cp36m-linux_x86_64.whl size=270918 sha256=00bd4511116bf7f5c2d6a98982921eccf0d9e97b6327b0fd9fcb7de21b55ff67
  Stored in directory: /home/rzwitch/.cache/pip/wheels/6e/53/3d/5a93174b38712013b3a3b3df15ea2a5144bd11b22edb84a14b
  Building wheel for moviepy (setup.py) ... done
  Created wheel for moviepy: filename=moviepy-1.0.3-py3-none-any.whl size=110727 sha256=505a4f72e028329e7069af08750ff64ebb666496b179d178b64e070b8eddfebb
  Stored in directory: /home/rzwitch/.cache/pip/wheels/be/dc/17/8b4d5a63bcd05dc44db7da57e193372ccd333617293f9deebe
  Building wheel for pyyaml (setup.py) ... done
  Created wheel for pyyaml: filename=PyYAML-5.3.1-cp36-cp36m-linux_x86_64.whl size=44621 sha256=ebe3207d6fb8e6638ae6d92f7bddfc2d8acb7e41f285b2668883cc5213eade7d
  Stored in directory: /home/rzwitch/.cache/pip/wheels/e5/9d/ad/2ee53cf262cba1ffd8afe1487eef788ea3f260b7e6232a80fc
  Building wheel for proglog (setup.py) ... done
  Created wheel for proglog: filename=proglog-0.1.9-py3-none-any.whl size=6146 sha256=c6869b2deeec4526abd68dbd60bbf3748c09f02c1eae9cc20901218faeb2b356
  Stored in directory: /home/rzwitch/.cache/pip/wheels/e7/11/a0/7e65f734d33043735a557b1244569cca327353db9068158076
  Building wheel for gast (setup.py) ... done
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7539 sha256=c39061ae8af8d9840cbc9f8ce4e9960ade899a8054d990cbee2f0d9e81ba15cd
  Stored in directory: /home/rzwitch/.cache/pip/wheels/19/a7/b9/0740c7a3a7d1d348f04823339274b90de25fbcd217b2ee1fbe
  Building wheel for absl-py (setup.py) ... done
  Created wheel for absl-py: filename=absl_py-0.9.0-py3-none-any.whl size=121931 sha256=ebf716db0fc59f63711a7eb10d1bd48eec14d75ebbaa9ed456329e55e33b4207
  Stored in directory: /home/rzwitch/.cache/pip/wheels/c3/af/84/3962a6af7b4ab336e951b7877dcfb758cf94548bb1771e0679
  Building wheel for termcolor (setup.py) ... done
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4830 sha256=a10b8dae9759fa3dedb868cbce2e298f47dbd492638561a3f07b119e477fbda5
  Stored in directory: /home/rzwitch/.cache/pip/wheels/93/2a/eb/e58dbcbc963549ee4f065ff80a59f274cc7210b6eab962acdc
  Building wheel for wrapt (setup.py) ... done
  Created wheel for wrapt: filename=wrapt-1.12.1-cp36-cp36m-linux_x86_64.whl size=69762 sha256=36e0b11ee350b4fcc202fd2387d90cc945a5d2818ba775de7f0a79f507439355
  Stored in directory: /home/rzwitch/.cache/pip/wheels/32/42/7f/23cae9ff6ef66798d00dc5d659088e57dbba01566f6c60db63
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=eb6dffa884d364f781aa902eb7765763a68a438b10a86136563cff85fd7a6693
  Stored in directory: /home/rzwitch/.cache/pip/wheels/6e/9c/ed/4499c9865ac1002697793e0ae05ba6be33553d098f3347fb94
  Building wheel for validators (setup.py) ... done
  Created wheel for validators: filename=validators-0.15.0-py3-none-any.whl size=18371 sha256=af2d700b35cb772a181633df2f4f2db1db6b8e6c86a90c686641985b4ffe69f7
  Stored in directory: /home/rzwitch/.cache/pip/wheels/5c/7a/7a/d00ad8409291275019b261d755911ca7b02f4c49c5c2bc361f
Successfully built lmdb moviepy pyyaml proglog gast absl-py termcolor wrapt future validators
Installing collected packages: pyparsing, kiwisolver, numpy, six, python-dateutil, cycler, matplotlib, scipy, h5py, pytz, pandas, pycparser, cffi, cryptography, Pillow, pyyaml, keras, lmdb, decorator, tqdm, chardet, urllib3, idna, requests, proglog, imageio, imageio-ffmpeg, moviepy, threadpoolctl, joblib, scikit-learn, opencv-python, protobuf, grpcio, werkzeug, absl-py, zipp, importlib-metadata, markdown, tensorboard, keras-preprocessing, astor, keras-applications, gast, opt-einsum, tensorflow-estimator, termcolor, wrapt, google-pasta, tensorflow, pathtools, watchdog, base58, packaging, cachetools, future, click, jmespath, docutils, botocore, tzlocal, tornado, blinker, toml, enum-compat, s3transfer, boto3, ipython-genutils, traitlets, MarkupSafe, jinja2, wcwidth, prompt-toolkit, ptyprocess, pexpect, pickleshare, parso, jedi, backcall, pygments, ipython, jupyter-core, attrs, pyrsistent, jsonschema, nbformat, pyzmq, jupyter-client, ipykernel, terminado, Send2Trash, prometheus-client, testpath, entrypoints, webencodings, bleach, defusedxml, pandocfilters, mistune, nbconvert, notebook, widgetsnbextension, ipywidgets, pydeck, toolz, altair, validators, streamlit
Successfully installed MarkupSafe-1.1.1 Pillow-7.1.2 Send2Trash-1.5.0 absl-py-0.9.0 altair-4.1.0 astor-0.8.1 attrs-19.3.0 backcall-0.2.0 base58-2.0.1 bleach-3.1.5 blinker-1.4 boto3-1.14.10 botocore-1.17.10 cachetools-4.1.0 cffi-1.14.0 chardet-3.0.4 click-7.1.2 cryptography-2.9.2 cycler-0.10.0 decorator-4.4.2 defusedxml-0.6.0 docutils-0.15.2 entrypoints-0.3 enum-compat-0.0.3 future-0.18.2 gast-0.2.2 google-pasta-0.2.0 grpcio-1.30.0 h5py-2.10.0 idna-2.9 imageio-2.8.0 imageio-ffmpeg-0.4.2 importlib-metadata-1.6.1 ipykernel-5.3.0 ipython-7.15.0 ipython-genutils-0.2.0 ipywidgets-7.5.1 jedi-0.17.1 jinja2-2.11.2 jmespath-0.10.0 joblib-0.15.1 jsonschema-3.2.0 jupyter-client-6.1.3 jupyter-core-4.6.3 keras-2.4.3 keras-applications-1.0.8 keras-preprocessing-1.1.2 kiwisolver-1.2.0 lmdb-0.98 markdown-3.2.2 matplotlib-3.2.2 mistune-0.8.4 moviepy-1.0.3 nbconvert-5.6.1 nbformat-5.0.7 notebook-6.0.3 numpy-1.19.0 opencv-python-4.2.0.34 opt-einsum-3.2.1 packaging-20.4 pandas-1.0.5 pandocfilters-1.4.2 parso-0.7.0 pathtools-0.1.2 pexpect-4.8.0 pickleshare-0.7.5 proglog-0.1.9 prometheus-client-0.8.0 prompt-toolkit-3.0.5 protobuf-3.12.2 ptyprocess-0.6.0 pycparser-2.20 pydeck-0.4.0b2 pygments-2.6.1 pyparsing-2.4.7 pyrsistent-0.16.0 python-dateutil-2.8.1 pytz-2020.1 pyyaml-5.3.1 pyzmq-19.0.1 requests-2.24.0 s3transfer-0.3.3 scikit-learn-0.23.1 scipy-1.5.0 six-1.15.0 streamlit-0.57.0 tensorboard-1.15.0 tensorflow-1.15.2 tensorflow-estimator-1.15.1 termcolor-1.1.0 terminado-0.8.3 testpath-0.4.4 threadpoolctl-2.1.0 toml-0.10.1 toolz-0.10.0 tornado-5.1.1 tqdm-4.46.1 traitlets-4.3.3 tzlocal-2.1 urllib3-1.25.9 validators-0.15.0 watchdog-0.10.2 wcwidth-0.2.5 webencodings-0.5.1 werkzeug-1.0.1 widgetsnbextension-3.5.1 wrapt-1.12.1 zipp-3.1.0
(gandemo) rzwitch@threadripper:~/github_work/demo-face-gan$ streamlit run app.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.0.199:8501
```

I suspect you might have been using a version of Python greater than 3.6? There's a separate issue opened just now #7 that tensorflow is also compatible with 3.6 (contrary to what our README says), but overall it does seem like the GAN demo does work.

Happy to leave this issue open for you to comment, or you can close it upon successful installation with Python 3.6.

Best,
Randy

**Comment by randyzwitch** [comment] 2020-06-25 18:59
I've also confirmed it works with Python 3.7, so it looks like the issue is that the version of Tensorflow we specify isn't supported by 3.8. I can pursue updating the app to support TF on Python 3.9 as a separate task.

**Closed** 2020-06-29 14:15 UTC
